### ISSUE TITLE
Missing Patch Notes and Undocumented Changes

### ISSUE THREAD

**Issue by Elitesparkle** [stuaroo/heroes-patch-notes#1]
The following Patch Notes are missing on [Heroes Patch Notes](https://heroespatchnotes.com/):
- [HEROES OF THE STORM PATCH NOTES - SEPTEMBER 20, 2023](https://news.blizzard.com/en-us/heroes-of-the-storm/23999073/heroes-of-the-storm-patch-notes-september-20-2023) (2.55.3.91020)
- UNDOCUMENTED CHANGES - SEPTEMBER 23, 2023 (2.55.3.91081)
- UNDOCUMENTED CHANGES - SEPTEMBER 25, 2023 (2.55.3.91093)
- [HEROES OF THE STORM PTR PATCH NOTES - OCTOBER 23, 2023](https://news.blizzard.com/en-us/heroes-of-the-storm/24017507/heroes-of-the-storm-ptr-patch-notes-october-23-2023)
- [HEROES OF THE STORM PATCH NOTES - NOVEMBER 16, 2023](https://news.blizzard.com/en-us/heroes-of-the-storm/24031812/heroes-of-the-storm-patch-notes-november-16-2023) (2.55.4.91368)
- UNDOCUMENTED CHANGES - NOVEMBER 22, 2023 (2.55.4.91418)
- [HEROES OF THE STORM PTR PATCH NOTES - JANUARY 17, 2024](https://news.blizzard.com/en-us/heroes-of-the-storm/24056177/heroes-of-the-storm-ptr-patch-notes-january-17-2024)
- [HEROES OF THE STORM LIVE PATCH NOTES - FEBRUARY 6, 2024](https://news.blizzard.com/en-us/heroes-of-the-storm/24061887/heroes-of-the-storm-live-patch-notes-february-6-2024) (2.55.4.91769)

### UNDOCUMENTED CHANGES - SEPTEMBER 20, 2023 (2.55.3.91020)

Battlegrounds
- Experience Globes can no longer be disjointed by teleporting.
- Braxis Holdout's Banelings will no longer be prevented from exploding themselves on impact if they are Blinded.

Abathur
- Fixed an issue that caused Evolutionary Link's Shield to also be created on the previous target of Ultimate Evolution while Ultimate Evolution is active.

Blaze
- Fixed an issue that caused Suppressive Fire to not reduce healing dealt.

Gall
- Fixed an issue that caused Shifting Nether to also teleport an Ultimate Evolution copy of Cho if it was nearby when cast.

Kharazim
- Fixed an issue that caused Air Ally to not grant Spellpower to Gall.

Li-Ming
- Fixed an issue that caused Glass Cannon to not increase healing dealt.
- Fixed an issue that caused Power Hungry to not increase healing dealt.

Medivh
- Fixed an issue that caused Force of Magic to not increase healing dealt.

Mephisto
- Fixed an issue that caused Abhorred Skull to not increase healing dealt by the correct amount.

Murky
- Fixed an issue that caused Living the Dream to not increase healing dealt.

Nazeebo
- Fixed an issue that caused Thing of the Deep to not increase healing dealt.
- Fixed an issue that caused Soul Harvest to not increase healing dealt.

Ragnaros
- Fixed an issue that caused Lava Wave to collect reduced value Experience Globes as though they were full value Experience Globes.

Zarya
- Fixed an issue that caused Defensive Shielding to not apply correctly on Shield Ally expiring.

Interface

- Fixed an issue that caused the Target Info Panel to display incorrectly after being moved.

### UNDOCUMENTED CHANGES - SEPTEMBER 23, 2023 (2.55.3.91081)

Interface
- Fixed a typo in the Battlegrounds list for Storm League.

Alexstrasza
- Fixed an issue that caused Dragon Scales to be temporarily disabled after activation when Rooted, Stunned or Silenced.

Brightwing
- Fixed an issue that caused Brightwing to be able to cast Phase Shift on allied Hero in Stasis.

Johanna
- Fixed an issue that prevented Heaven's Fury from healing Invulnerable allied Heroes.

Tychus
- Fixed an issue that caused Armor Piercing Rounds to display in the Status Bar.

### UNDOCUMENTED CHANGES - SEPTEMBER 25, 2023 (2.55.3.91093)

General
- Block stacks maximum set to 4.

Brightwing
- Fixed an issue causing Safety Dust to not increase healing from Blink Heal and Soothing Mist.

Rehgar
- Fixed an issue causing Rising Storm to not be reset when Rehgar recasts Lightning Shield.

### UNDOCUMENTED CHANGES - NOVEMBER 16, 2023 (2.55.4.91368)

Collection
- Garrosh's Into the Fray added to Hero Page.
- Spectral Butcher is no longer flagged as a Limited Time Item.
- Spectral Buccaneer Falstad is no longer flagged as a Limited Time Item.
- Deathranger Nova is no longer flagged as Limited Time Item.
- Dark Mecha Rehgar is no longer flagged as a Limited Time Item.
- Dark Mecha Tyrael is no longer flagged as a Limited Time Item.
- Footman Varian is no longer flagged as Limited Time Item.

Battlegrounds 
- Fixed an issue causing Gnolls and Hellbats to not reduce the armor of Genji with Dodge active or Qhira with Upstage active.

General
- Fixed an issue causing Regeneration Globe's healing to be modified by the targets Spell Power if the unit does not use Mana.
- Fixed an issue causing Regeneration Globe's healing to display floating combat text if the unit does not use Mana.
- Fixed an issue causing Heroes in Vehicles to gain bonuses from being stationary while Stealthed.
- Targets may now be revealed by Ability damage from up to 10 different casters at a time.
- All forms of generic Block will now display Block visuals.

Alextrasza
- Dragonqueen Basic Attack will now reveal the area immediately inside Alexstrasza.
- Ancient Flame icon updated and then reverted.

Anduin
- Holy Nova now reveals enemy targets hit for 2 seconds.
- Divine Star now reveals enemy targets hit for 2 seconds.
- Chastise target reveal updated from 1.25 seconds to 2 seconds.
- Light Bomb now reveals targets hit for 2 seconds.

Anub'arak
- Burrow Charge will now reveal the effect area, extended by 1 for 0.75 seconds.
- Urticating Spines area reveal updated from area for 1 second to area extended by 1 for 0.75 seconds.
- Burning Beetles is now flagged as a Trait Talent.

Artanis
- Blade Dash will now reveal targets hit for 2 seconds.
- Suppression Pulse will now reveal targets hit for 2 seconds.

Arthas
- Sindragosa will now reveal targets hit for 2 seconds.

Cho
- Fuel for the Flame icon updated.

Deckard
- Horadric Cube now reveals targets hit.

Diablo
- Fire Stomp no longer grants vision-obscured sight.
- Fire Stomp now reveals the area extended by 1 for 0.75 seconds.

Falstad
- Hammerang Reactivation now reveals the area extended by 1 for 0.75 seconds.
- Hammerang Return area reveal updated from 2.625 for 0.33 seconds to area (0.65) extended by 1 for 0.75 seconds.
- Hammerang outward area reveal updated from 2.625 for 0.33 seconds to area (1.25 x 2.1) extended by 1 for 0.75 seconds.
- Frequent Flyer icon updated and then reverted.
- Sutained Winds icon updated and then reverted.

Fenix
- Plasma Cutter will now reveal targets hit for 2 seconds.
- Planet Cracker will now reveal targets hit for 2 seconds.
- The splash of Arsenal Synergy's Phase Bomb will no longer reveal targets hit.
- Mobile Offensive icon updated and then reverted.
- Singularity Charge icon updated and then reverted.
- Offensive Cadence icon updated and then reverted.
- Divert Power: Weapons icon updated and then reverted.

Garrosh
- Seasoned Soldier icon updated.
- Mortal Combo icon updated.
- Earthshaker icon updated.

Hogger
- Seeing Red is now flagged as a Passive Talent.
- Seeing Red icon updated.
- Seeing Red moved to the last slot in the Tier.

Illidan
- Dive now reveal the enemy target for 2 seconds.
- Sweeping Strikes now reveal the targets for 2 seconds.

Johanna
- Holy Fury is now flagged as a Condemn Talent.

Junkrat
- Basic Attack Splash area reveal is now extended by 1.

Kerrigan
- Ultralisk Splash no longer reveals the target.

Leoric
- Burning Despair is now flagged as a Drain Hope Talent.

Li Li
- Tooltip for Healing Brew fixed.

Lt. Morales
- Tooltip for Bedside Manner fixed.

Lúcio
- Good Vibrations icon updated.

Lunara
- Let Them Wither icon updated.
- Siphoning Toxin and Nature's Culling location in Tier swapped.

Mal'Ganis
- The Night Beckons icon updated and then reverted.

Malfurion
- Lunar Shower icon updated.

Medivh
- Force of Magic icon updated.

Murky
- Octo-Grab damage target reveal updated from 0.75 radius for 1 second to target for 2 seconds.

Nova
- Fixed an issue causing Permanent Cloak to not be applied when available after selecting Apollo Suit.

Samuro
- Mirror Image & Image Transmission will no longer cause Samuro and his Mirror Images to have Experience Globes magentise towards them while inside a Shrub for 2 seconds.
- Burning Blade area reveal is now extended by 1.

Sgt. Hammer
- Maelstrom Rounds icon updated.
- Advanced Artillery icon updated
- Ambush icon updated.

Stitches
- Flare Up is now flagged as a Trait Talent.

Stukov
- Fetid Touch icon updated and then reverted.
- Reactive Ballistospores icon updated.

Sylvanas
- Life Drain icon updated.
- Remorseless is now flagged as a Trait Talent.
- Life Drain is now flagged as a Trait Talent.

The Butcher
- Hamstring area reveal updated from area for 0.5 seconds to area extended by 1 for 0.75 seconds.
Furnace Blast area reveal updated from area for 0.5 seconds to area extended by 1 for 0.75 seconds.

The Lost Vikings
- Tooltip for Viking Bribery updated to no longer display stacks in the Talents Panel (English only).

Thrall
- Maelstrom Weapon icon updated.

Tracer
- Alpha of the Ammo Bar while Locked and Loaded is active changed from 90-140 to 110-160.
- Untouchable icon updated and then reverted.

Tyrael
- Burning Halo is now flagged as an El'Druin's Might Talent.
- Horadric Reforging is now classed as an El'Druin's Might Talent.

Tyrande
- Fixed an issue causing Shadowstalk to not apply to targets featuring passive Cloak effects.
- Shadowstalk will now remove any active reveals on the target.
- Tooltip for Huntress' Fury fixed.

Uther
- Holy Fire icon updated and then reverted.

Zarya
- Expulsion Zone now reveals targets hit.

### UNDOCUMENTED CHANGES - NOVEMBER 22, 2023 (2.55.4.91418)

Anub'arak
- Fixed an issue causing Cocoon's duration to not be displayed correctly.

D.Va
- Fixed an issue causing Ablative Armor and Diverting Power to display incorrectly in the Death Recap.

Dehaka
- Fixed an issue causing Lurker Strain knockback to cause animation cancels.

Greymane
- Fixed an issue causing Alpha Killer to damage non-Heroes.

Jaina
- Fixed an issue causing rost Shards to not allow Frost Bolt to hit targets close to each other.

Maiev
- Fixed an issue causing Containment Disc duration to not be displayed correctly.

Murky
- Fixed an issue causing Octograb's visuals to not be visible to Murky when the target is inside a Shrub and Murky is not inside the Shrub.

Sonya
- Fixed an issue causing Leap's Unstoppable to not last the full duration of no-distance Leap casts.

Zagara
- Fixed an issue causing Baneling Barrage to display incorrectly in the Death Recap.

### PTR UNDOCUMENTED CHANGES - 17 JANUARY, 2024

Interface
- Several Talents have been updated to have their tooltips attached to their related Ability, or had their order updated to match the order in which the Talent is obtained.

General
- When Blinds prevent damage to Heroes, the Healing Score of the Hero who placed the Blind is increased for the damage prevented.

Auriel
- Fixed an issue causing Searing Light to not grant Energy when hitting a Protected enemy.

Garrosh
- Unrivaled Strength is now an additive bonus.

Jaina
- Water Elemental's Frostbolts will now behave consistently with Jaina's Frostbolts.

Tracer
- Locked and Loaded will now cause Tracer's Basic Attacks to display as Criticals while active.

**Comment by stuaroo** [comment]
Little confused on an undocumented change on 2023-11-16 patch.  The official notes have this for battleground changes:

* Fixed an issue that caused Gnolls/Hellbats to reduce the armor of Evading targets.

While one of the undocumented notes says:

* Fixed an issue causing Gnolls and Hellbats to not reduce the armor of Genji with Dodge active or Qhira with Upstage active.

These seem to be opposites; is the latter meaning that the change wasn't applied to Genji/Qhira specifically?  I realize this is rather old at this point, and you may not know or remember the specifics, so I'll leave this one out for now until/unless we can get a little more detail.

**Comment by Elitesparkle** [comment]
That's fine. I'll let you know if I find more information about that change.

I noticed that some of the Patch Notes mentioned here are missing in the [Patch Summary](https://heroespatchnotes.com/patch/summary.html) section.

[Here](https://www.reddit.com/r/CursedHollow/comments/1c5wb1z/heroes_of_the_storm_ptr_update_20240417/) you can find undocumented changes for [HEROES OF THE STORM PTR PATCH NOTES - APRIL 16, 2024](https://news.blizzard.com/en-us/heroes-of-the-storm/24077220/heroes-of-the-storm-ptr-patch-notes-april-16-2024).

Thank you for updating the site!

**Comment by stuaroo** [comment]
So the Patch Summary by default was only creating sections for major patches and balance updates (as those used to be the main types of patches we'd get), and would ignore hotfix and undocumented patches since they were relatively rare.  Since these positions have reversed in the last few years, I may need to revisit how this works.  Are there some major changes in particular you'd like to see highlighted there?

Thanks for the link to those extra undocumented changes, I'll start working on adding those as well!

**Comment by Elitesparkle** [comment]
I see. I think it's fine as it is. Thanks for the explanation.
